### PR TITLE
jacoco 0.8.7 for JDK 17 support

### PR DESCRIPTION
**Pull request by gokhanoner**
resolves https://github.com/sbt/sbt-jacoco/issues/138

### CODE REVIEW

**Comment by gokhanoner** [comment]
@SethTisue added

**Comment by gokhanoner** [comment]
@SethTisue upgraded mockito version, run tests locally, seems OK. lets give it a try

**Comment by gokhanoner** [comment]
@SethTisue any help appreciated. apparently build try to use sbt 1.1.6 for JAVA 17 but for that it needs to use 1.4.9. How/where can I change that ?

**Comment by SethTisue** [comment]
`build.sbt` has

```
    // compile this plugin against sbt 1.1.6                                                                            
    pluginCrossBuild / sbtVersion := "1.1.6"                                                                            
```

**Comment by gokhanoner** [comment]
@SethTisue lets try again, I removed pluginCrossBuild section

**Comment by SethTisue** [comment]
> I know, is it OK to remove it?

I would think so? at least I don't see why not

**Comment by gokhanoner** [comment]
@SethTisue I also upgraded test scala versions as well. Pls run again.

**Comment by SethTisue** [comment]
if the 1.4.9 + 2.12.14 combo doesn't work, you might try 1.5.5 + 2.12.15

**Comment by SethTisue** [comment]
`git grep 2\\.10` turns up a bunch of `scala-2.10`s that need to be changed to `scala-2.12`, I believe

**Comment by gokhanoner** [comment]
@SethTisue yeah, changed those + upgraded to sbt 1.5.5, tested with same build options locally, both java 8 & 17, hopefully it'll pass this time 👍🏽

**Pull request merged**
