### PR TITLE
improved aggregation, jacoco version updated

### PR DESCRIPTION
**Pull request by pshirshov**

### CODE REVIEW

**Comment by KoenDG** [comment]
Gonna subscribe because I'd like to see it working.

Looks like the travis build failed because this PR changes the Scala version to 2.11.7 and the Travis build runs on 2.10.4, hardcoded.

https://travis-ci.org/sbt/jacoco4sbt/jobs/115345634/config

**Comment by benmccann** [comment]
This PR is really doing a lot of things. It'd be easier to review if these were separate commits. It would need to be rebased before it can be merged

**Comment by pshirshov** [comment]
Okay, will try to come back to this thing one day... Though there is not "a lot" of things, really

**Comment by eed3si9n** [comment]
Closing this due to inactivity.

**Pull request closed without merging**
